export const FEEDBACK_EVENTS = Object.freeze({
  NAVIGATE: "navigation.commit",
  ACTION_CONFIRM: "action.confirm",
  ACTION_DENY: "action.deny",
  SELECTION: "action.selection",
  FILTER: "action.filter",
  PURCHASE: "action.purchase",
  EQUIP: "action.equip",
  DUEL_LAUNCH: "action.duel.launch",
  RETRY: "action.retry",
  ACHIEVEMENT: "achievement.unlocked",
  COUNTDOWN_TICK: "round.countdown.tick",
  COUNTDOWN_GO: "round.countdown.go",
  HIT: "round.hit",
  MISS: "round.miss",
  GUARDED_MISS: "round.guard",
  STREAK_MILESTONE: "round.streak.milestone",
  POWER_READY: "power.ready",
  POWER_ACTIVATE: "power.activate",
  TIME_WARNING: "round.time.low",
  REWARD: "reward.granted",
  RANK_CHANGE: "rank.changed",
  TEST: "settings.test",
  ARMORY_PART_HOVER: "armory.part.hover",
  ARMORY_PART_INSTALL: "armory.part.install",
  ARMORY_BAY_ACTIVATE: "armory.bay.activate",
  ARMORY_RANGE_START: "armory.range.start",
})

export const FEEDBACK_EVENT_NAMES = Object.freeze(Object.values(FEEDBACK_EVENTS))
